#!/usr/bin/env bash
#
# CLI tool for GitHub release management
#
# Note:
#   For conventional-github-releaser to work you'll need to setup a new GitHub
#   app token, then add the `CONVENTIONAL_GITHUB_RELEASER_TOKEN` environment
#   variable to your shell. You can find more details here:
#   https://github.com/stevemao/$conventionalGithubReleaser#setup-token-for-cli
#
# Usage:
#   githubrelease -h
#
# defaults to conventional-recommended-bump
# and optional argument preset `angular`/ `jquery` ...
# defaults to conventional-commits-detector
#-------------------------------------------------------------------------------
# Does the following:
#  1. pull from remote origin for master and develop branches
#  2. rebase master onto develop
#  3. rebase develop onto master
#  4. grabs the short SHA of master
#  5. updates changelog
#  6. bumps version number
#  7. commits changes
#  8. creates a version tag
#  9. pushes master and tag to remote
# 10. rebase master onto develop
# 11. pushes develop to remote
# 12. creates a release on github
# 13. output message "Landed in <shortsha>"
#-------------------------------------------------------------------------------

set -e

scriptDir=`_githubreleasehelper -p`
binDir="$scriptDir/node_modules/.bin"
chalk="$binDir/chalk"
conventionalChangelog="$binDir/conventional-changelog"
conventionalCommitsDetector="$binDir/conventional-commits-detector"
conventionalGithubReleaser="$binDir/conventional-github-releaser"
conventionalRecommendedBump="$binDir/conventional-recommended-bump"
json="$binDir/json"
trash="$binDir/trash"
shortsha=""


# ------------------------------------------------------------------------------
# Helper commands
# ------------------------------------------------------------------------------
# Universal logger for this script
log() {
  local output="$counter"
  [[ $counter -lt 10 ]] && output="$counter "

  $chalk cyan "[step: $output] $1"

  [[ "$1" != "startOnMaster" ]] && [[ "$1" != "startOnDevelop" ]] && increment
}

# Step counter
increment() {
  ((counter+=1))
}

# Get the current Git branch
gitCurrBranch() {
  ref=$(command git symbolic-ref HEAD 2> /dev/null) || \
  ref=$(command git rev-parse --short HEAD 2> /dev/null) || return
  echo "${ref#refs/heads/}"
}

# ------------------------------------------------------------------------------
# Script commands
# ------------------------------------------------------------------------------
# Switch the current branch to <master>
startOnMaster() {
  log "startOnMaster"
  if [ $(gitCurrBranch) != $master ]; then
    git checkout $master
  fi
}

# Switch the current branch to <develop>
startOnDevelop() {
  log "startOnDevelop"
  if [ $(gitCurrBranch) != $develop ]; then
    git checkout $develop
  fi
}

# Pull latest changes from <master> and <develop> using rebase
updateBranches() {
  log "updateBranches"
  git pull --rebase origin $master &&
  git checkout $develop &&
  git pull --rebase origin $develop
}

# Rebase the <develop> branch onto <master>
rebaseDevelopOntoMaster() {
  log "rebaseDevelopOntoMaster"
  git rebase $develop
}

# Run npm tests
runTests() {
  log "runTests"
  $trash node_modules &>/dev/null
  npm install --silent
  npm run test
}

# Get the short sha
getShortSha() {
  echo "$(git rev-parse --short HEAD)"
}

# Make a backup of the package.json
backupPackage() {
  log "backupPackage"
  cp package.json _package.json
}

# Use npm to bump the version of the package.json
bumpPackage() {
  log "bumpPackage"
  npm --no-git-tag-version version ${bump} &>/dev/null
}

# Generate a changelog entry and save it to <changelog>
updateChangelog() {
  log "updateChangelog"
  local changelog="./CHANGELOG.md"
  if [[ ! -f "$changelog" ]]; then
    touch "$changelog"
  fi &&
  $conventionalChangelog -i CHANGELOG.md -s -p ${preset}
  if [[ -z $argnoprompt ]]; then
    echo ""
    $chalk yellow "Review your \"$changelog\"."
    $chalk yellow "Would you like to continue?"
    select yn in "Yes" "No"; do
        case $yn in
            Yes ) break;;
            No ) exit;;
        esac
    done
  fi
}

# Add the <changelog> to Git and commit it
addChangelog() {
  log "addChangelog"
  local version=$(cat package.json | $json version)
  git add CHANGELOG.md
  git commit -m"docs(CHANGELOG): $version"
}

# Reset the package.json to the backup made earlier
resetPackage() {
  log "resetPackage"
  mv -f _package.json package.json
}

# Using npm, bump the package.json version, create new tag, and commit change
# to Git
npmBump() {
  log "npmBump"
  npm version ${bump} -m "chore(release): %s"
}

# Rebase the <master> branch onto <develop>
rebaseMasterOntoDevelop() {
  log "rebaseMasterOntoDevelop"
  git rebase $master
}

# Push <master> and <develop> branches and all tags to remote origin
pushAll() {
  log "pushAll"
  git push origin $master &&
  git push origin $develop &&
  git push --tags
}

# Cut a release on GitHub and append the changelog to the GitHub release
conventionalGitHubReleaser() {
  log "conventionalGitHubReleaser"
  $conventionalGithubReleaser -p ${preset}
}

landedMessage() {
  log "landedMessage"
  $chalk green "Landed in $shortsha"
}

# ------------------------------------------------------------------------------
#
# ------------------------------------------------------------------------------
# Defaults
defaultremote="origin"
defaultmaster="master"
defaultdevelop="develop"
defaultchangelog="CHANGELOG.md"
defaultstep=1

usage() {
  cat << EOF
usage: githubrelease options

Release a npm package to github.

FLAG OPTIONS:
   -h     Show this message.
   -v     Display the version of this script.
   -l     Generate a changelog entry and save it to <changelog>.
   -p     Push <master>, <develop>, and tags to <remote>.
   -u     Update <master> and <develop> branches from <remote> using rebase.
   -n     Do not display any prompts

ARGUMENT OPTIONS:
   -c     Location of the <changelog>. Defaults to 'CHANGELOG.md'.
   -m     The <master> branch. Defaults to 'master'.
   -d     The <develop> branch. Defaults to 'develop'.
   -r     The <remote> push and pull from. Defaults to 'origin'.
   -P     The preset style used to generate the changelog. Examples include
          ['angular' | 'jquery' ...]. Defaults to 'conventional-recommended-bump'.
   -s     Allows you to start at a specific step. Useful for when the script
          fails before completing all steps. See AVAILABLE STEPS below.
   -b     The semver you would like to use for the release (default: patch).
          Can be: [ major | minor | patch | v0.0.0 ]

AVAILABLE STEPS:
    1     Update <master> and <develop> branches from <remote> using rebase.
    2     Push <master>, <develop>, and tags to <remote>.
    3     Run 'npm test'
    4     Rebase <develop> onto <master>.
    5     Make a copy of 'package.json' to '_package.json'.
    6     Temporarily bump the semver of 'package.json'.
    7     Save a changelog entry to <changelog>.
    8     Commit <changelog> update to Git.
    9     Reset 'package.json' by moveing '_package.json' to 'package.json'.
   10     Run 'npm version' command, which bumps 'package.json' and creates a tag.
   11     Rebase <master> onto <develop>.
   12     Push <master>, <develop>, and tags to <remote>.
   13     Run 'conventional-github-releaser' to create a release in GitHub.
   14     Output landed message which contains the short sha of HEAD.

EXAMPLES:
   1. Update all branches
   2. Push changes from all branches
   3. Cut a release

   githubrelease -u
   githubrelease -p
   githubrelease -b patch
EOF
}
# Argument variables
arglog=
argpull=
argpush=
argnoprompt=
argchangelog=
argmaster=
argdevelop=
argremote=
argpreset=
argstep=
argbump=

# Variables to use in script
changelog=
master=
develop=
remote=
preset=
step=
bump=

# Grab command line arguments and flags
while getopts "hvlupnc:r:m:d:P:s:b:" OPTION
do
  case $OPTION in
    h)
      usage
      exit 1
      ;;
    v)
      echo "githubrelease v$(_githubreleasehelper --version)"
      exit 1
      ;;
    l)
      arglog=1
      ;;
    u)
      argpull=1
      ;;
    p)
      argpush=1
      ;;
    n)
      argnoprompt=1
      ;;
    c)
      argchangelog=$OPTARG
      ;;
    r)
      argremote=$OPTARG
      ;;
    m)
      argmaster=$OPTARG
      ;;
    d)
      argdevelop=$OPTARG
      ;;
    P)
      argpreset=$OPTARG
      ;;
    s)
      argstep=$OPTARG
      ;;
    b)
      argbump=$OPTARG
      ;;
    ?)
      usage
      exit
      ;;
  esac
done

# Parse arguments and apply defaults if an argument was not passed
[[ -n $argchangelog ]] && changelog=$argchangelog || changelog=$defaultchangelog
[[ -n $argremote ]] && remote=$argremote || remote=$defaultremote
[[ -n $argmaster ]] && master=$argmaster || master=$defaultmaster
[[ -n $argdevelop ]] && develop=$argdevelop || develop=$defaultdevelop
[[ -n $argpreset ]] && preset=$argpreset || preset=$($conventionalCommitsDetector)
[[ -n $argstep ]] && step=$argstep || step=$defaultstep
# Check preset and default to "angular"
[[ "$($conventionalRecommendedBump -p ${preset} 2>&1)" == *"does not exist"* ]] && preset="angular"
[[ -n $argbump ]] && bump=$argbump || bump=$($conventionalRecommendedBump -p ${preset} 2> /dev/null)

counter=$step

# Config setup info
currVersion=$(cat package.json | $json version)
nextVersion=$(_githubreleasehelper --inc $currVersion --release $bump)

# Output config setup
$chalk cyan "========== CONFIG =========="
$chalk white << EOF
log           : $arglog
pull          : $argpull
push          : $argpush
changelog     : $changelog
remote        : $remote
master        : $master
develop       : $develop
preset        : $preset <detected: "$($conventionalCommitsDetector)", chosen: "$preset">
bump          : $bump <detected: "$($conventionalRecommendedBump -p $($conventionalCommitsDetector) 2> /dev/null)", chosen: "$bump">
currVersion   : $currVersion
nextVersion   : $nextVersion
counter       : $counter
step          : $step
noprompts     : $argnoprompt
EOF
$chalk cyan "============================"
if [[ -z $argnoprompt ]]; then
  echo ""
  $chalk yellow "Based on the config above would you like to continue?"
  select yn in "Yes" "No"; do
      case $yn in
          Yes ) break;;
          No ) exit;;
      esac
  done
fi

# githubrelease -l
# githubrelease -l -b minor
if [[ -n $arglog ]]; then
  backupPackage
  bumpPackage
  updateChangelog
  resetPackage
  exit 1
fi

# githubrelease -u
if [[ -n $argpull ]]; then
  startOnMaster && updateBranches &&
  exit 1
fi

# githubrelease -p
if [[ -n $argpush ]]; then
  pushAll &&
  exit 1
fi

# Run the release script
if [[ $step -le  1 ]]; then startOnMaster && updateBranches;           fi && # Step 1
if [[ $step -le  2 ]]; then pushAll;                                   fi && # Step 2
if [[ $step -le  3 ]]; then startOnDevelop && runTests;                fi && # Step 3
if [[ $step -le  4 ]]; then startOnMaster && rebaseDevelopOntoMaster;  fi && # Step 4
if [[ $step -ge  5 ]]; then startOnMaster;                             fi && # Step >= 5
if [[ $step -ge  5 ]]; then shortsha="$(getShortSha)";                 fi && # Step >= 5
if [[ $step -le  5 ]]; then backupPackage;                             fi && # Step 5
if [[ $step -le  6 ]]; then bumpPackage;                               fi && # Step 6
if [[ $step -le  7 ]]; then updateChangelog;                           fi && # Step 7
if [[ $step -le  8 ]]; then addChangelog;                              fi && # Step 8
if [[ $step -le  9 ]]; then resetPackage;                              fi && # Step 9
if [[ $step -le 10 ]]; then npmBump;                                   fi && # Step 10
if [[ $step -le 11 ]]; then startOnDevelop && rebaseMasterOntoDevelop; fi && # Step 11
if [[ $step -le 12 ]]; then pushAll;                                   fi && # Step 12
if [[ $step -le 13 ]]; then conventionalGitHubReleaser;                fi && # Step 13
if [[ $step -le 14 ]]; then landedMessage;                             fi && # Step 14
$chalk green "All done!" || $chalk red "Epic fail!"
